/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package universidadgrupo49.vistas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import universidadgrupo49.accesoADatos.AlumnoData;
import universidadgrupo49.accesoADatos.Conexion;
import universidadgrupo49.entidades.Alumno;

/**
 *
 * @author TenseiZX
 */
public class FormularioAlumno extends javax.swing.JInternalFrame {

    private AlumnoData ad;
//    private Alumno alumnoActual = null;  /////////////probando el metodo buscar del pelado con jdate chooser

    public FormularioAlumno(AlumnoData ad) {
        initComponents();
        AlumnoData objetoAlumno = new AlumnoData();
        objetoAlumno.mostrarAlumnos(jtTablaAlumno);
        this.ad = ad;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaAlumno = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtDocumentodni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtApellido = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbModificar = new javax.swing.JButton();
        jdcFechaNac = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jrbEstado = new javax.swing.JRadioButton();
        jbGuardar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jbLimpiar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtID = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 255));
        setTitle("Seccción alumnos");
        setMinimumSize(new java.awt.Dimension(44, 22));

        jPanel1.setBackground(new java.awt.Color(53, 166, 136));

        jtTablaAlumno.setBackground(new java.awt.Color(255, 255, 255));
        jtTablaAlumno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtTablaAlumno.setForeground(new java.awt.Color(0, 0, 0));
        jtTablaAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtTablaAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTablaAlumnoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTablaAlumno);

        jLabel1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel1.setText("Formulario de alumno");

        jtDocumentodni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDocumentodniActionPerformed(evt);
            }
        });
        jtDocumentodni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtDocumentodniKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel2.setText("DNI:");

        jbBuscar.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel3.setText("Apellido:");

        jtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtApellidoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel4.setText("Nombre:");

        jbModificar.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jbModificar.setText("Modificar:");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jdcFechaNac.setDateFormatString("yyyy-MM-dd");

        jLabel5.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel5.setText("Estado:");

        jbGuardar.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jbGuardar.setText("Guardar");
        jbGuardar.setEnabled(false);
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbEliminar.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbSalir.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbLimpiar.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jbLimpiar.setText("Limpiar");
        jbLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimpiarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel6.setText("Fecha de nacimiento:");

        jLabel7.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel7.setText("ID:");

        jtID.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(20, 20, 20)
                                .addComponent(jdcFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jtDocumentodni, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel1)
                                                    .addGap(26, 26, 26))
                                                .addComponent(jtID, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(20, 20, 20)
                                                .addComponent(jrbEstado)
                                                .addGap(107, 107, 107))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jbEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jbModificar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(jbLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtDocumentodni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbBuscar))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jdcFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrbEstado)
                            .addComponent(jLabel5))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbModificar)
                            .addComponent(jbGuardar))
                        .addGap(32, 32, 32))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbLimpiar)
                    .addComponent(jbEliminar))
                .addGap(30, 30, 30)
                .addComponent(jbSalir)
                .addGap(47, 47, 47))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimpiarActionPerformed
        //        jtid.setText("");
        jtDocumentodni.setText("");
        jtApellido.setText("");
        jtNombre.setText("");
        jtID.setText("");
        //        jtcampofecha.setText("");
        jdcFechaNac.setCalendar(null);//seteo a vacio
        jrbEstado.setSelected(false);//seteo a vacio
    }//GEN-LAST:event_jbLimpiarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed

        try {
            int cambiarAInactivo = Integer.parseInt(jtDocumentodni.getText());
            if (ad.buscarAlumnoPorDni(cambiarAInactivo) != null) {
                int msj = JOptionPane.showConfirmDialog(this, "estas seguro que desea eliminar este alumno?");

                if (msj == 0) {
                    ad.eliminarAlumno(ad.buscarAlumnoPorDni(cambiarAInactivo).getIdAlumno());
                    ad.mostrarAlumnos(jtTablaAlumno);
                    jtDocumentodni.setText("");
                    jtApellido.setText("");
                    jtNombre.setText("");
                    //                    jtcampofecha.setText("");
                    jdcFechaNac.setCalendar(null);//seteo a vacio
                    jrbEstado.setSelected(false);//seteo a vacio
                }

            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Error: 'eliminar' no puede haber campos vacios");
        }
        
        metodoLimpiar();
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed

        //        try {
        //
        //            ad.guardarAlumno(new Alumno(Integer.parseInt(jtDocumentodni.getText()), jtApellido.getText(), jtNombre.getText(), jdcFechaNac.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(), jrbEstado.isSelected()));
        //            ad.mostrarAlumnos(jtTablaAlumno);
        //
        //        } catch (NumberFormatException ex) {
        //            JOptionPane.showMessageDialog(null, "Error: Guardar, No puede haber campos vacios");
        //        } catch (NullPointerException exe) {
        //            JOptionPane.showMessageDialog(this, "error al guardar, entradas duplicadas");
        //        }
        //
        //        jtDocumentodni.setText("");
        //        jtApellido.setText("");
        //        jtNombre.setText("");
        //
        //        jdcFechaNac.setCalendar(null);
        //        jrbEstado.setSelected(false);
        /////////////////////////////////////////////////////////////////////////////////////////////////////
        //        try{
        //        Integer dni=Integer.parseInt(jtDocumentodni.getText());
        //
        //        String nombre=jtNombre.getText();
        //        String apellido=jtApellido.getText();
        //        if(nombre.isEmpty()||apellido.isEmpty()){
        //        JOptionPane.showMessageDialog(this,"no puede haber campos vacios");
        //        metodoLimpiar();
        //        return;
        //        }
        //
        //        java.util.Date sfecha=jdcFechaNac.getDate();
        //        LocalDate fechaNac=sfecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        //        Boolean estado=jrbEstado.isSelected();
        //        if(alumnoActual==null){
        //
        //            alumnoActual=new Alumno(dni, apellido, nombre, fechaNac, estado);
        //            ad.guardarAlumno(alumnoActual);
        //        }else{
        //
        //        alumnoActual.setDni(dni);
        //        alumnoActual.setApellido(apellido);
        //        alumnoActual.setNombre(nombre);
        //        alumnoActual.setFechaNacimiento(fechaNac);
        //        ad.ModificarAlumno(alumnoActual);
        //        }
        //
        //        }catch(NumberFormatException ex){
        //        JOptionPane.showMessageDialog(this, "debe ingresar un dni valido");
        //        metodoLimpiar();
        //        }
        ////////////////////////////////////////////////////////////////////////////////
        try {

            ad.guardarAlumno(new Alumno(Integer.parseInt(jtDocumentodni.getText()), jtApellido.getText(), jtNombre.getText(), jdcFechaNac.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(), jrbEstado.isSelected()));
            ad.mostrarAlumnos(jtTablaAlumno);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "campos vacios");
        }

        metodoLimpiar();
        
        ad.mostrarAlumnos(jtTablaAlumno);

    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed

        //        AlumnoData objetoAlumno = new AlumnoData();
        //
        //        try {
        //
        //            objetoAlumno.ModificarAlumno(new Alumno(Integer.parseInt(jtid.getText()), Integer.parseInt(jtDocumentodni.getText()), jtApellido.getText(), jtNombre.getText(), jdcFechaNac.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(), jrbEstado.isSelected()));
        //
        //            objetoAlumno.mostrarAlumnos(jtTablaAlumno);
        //        } catch (NumberFormatException ex) {
        //            JOptionPane.showMessageDialog(null, "Error: Numberformat no puede haber campos vacios");
        //        } catch (NullPointerException ex) {
        //            JOptionPane.showMessageDialog(null, "Error: Null no puede haber campos vacios");
        //        }
        //
        //        jtDocumentodni.setText("");
        //        jtApellido.setText("");
        //        jtNombre.setText("");
        //        jtcampofecha.setText("");
        //        jdcFechaNac.setCalendar(null);//seteo a vacio
        //        jrbEstado.setSelected(false);//seteo a vacio
        //        jtid.setText("");
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//        Alumno alumnoActual=null;
//        try {
//
//            Integer dni = Integer.parseInt(jtDocumentodni.getText());
//            String apellido = jtApellido.getText();
//            String nombre = jtNombre.getText();
//            if (nombre.isEmpty() || apellido.isEmpty()) {
//
//                JOptionPane.showMessageDialog(null, "No puede haber campos vacios ");
//                return;
//            }
//            java.util.Date sfecha = jdcFechaNac.getDate();
//            LocalDate fachaNac = sfecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
//            Boolean estado = jrbEstado.isSelected();
//            if (alumnoActual == null) {
//
//                alumnoActual = new Alumno(dni, apellido, nombre, fachaNac, estado);
//                ad.guardarAlumno(alumnoActual);
//            } else {
//                alumnoActual.setDni(dni);
//                alumnoActual.setApellido(apellido);
//                alumnoActual.setNombre(nombre);
//                alumnoActual.setFechaNacimiento(fachaNac);
//                ad.ModificarAlumno(alumnoActual);
//            }
//
//        } catch (NumberFormatException ex) {
//            JOptionPane.showMessageDialog(null, "Debe ingresar un dni valido ");
//
//        }
//        ad.mostrarAlumnos(jtTablaAlumno);
//
//        jtDocumentodni.setText("");
//        jtApellido.setText("");
//        jtNombre.setText("");
//
//        jdcFechaNac.setCalendar(null);//seteo a vacio
//        jrbEstado.setSelected(false);//seteo a vacio
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
           try{ 

            if (!jtNombre.getText().equals("") && !jtApellido.getText().equals("") && !jtDocumentodni.getText().equals("") && !jtID.getText().equals("")&&jdcFechaNac.getDate()!=null) {
            AlumnoData alu = new AlumnoData();
            String nombre, apellido;
            int dni, idalu;
            boolean estado;
            LocalDate fecha;
            idalu = Integer.parseInt(jtID.getText());
            nombre = jtNombre.getText();
            apellido = jtApellido.getText();
            dni = Integer.parseInt(jtDocumentodni.getText());
            if (jrbEstado.isSelected()) {
                estado = true;
            } else {
                estado = false;
            }
            fecha = jdcFechaNac.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            Alumno alumno = new Alumno(idalu, dni, apellido, nombre, fecha, estado);
            alu.ModificarAlumno(alumno);
        } else {
            JOptionPane.showMessageDialog(null, "los campos deben estar cargados");

        }
        
           } catch(NumberFormatException ex){
           JOptionPane.showMessageDialog(this, "Error: se excedio el numero de caracteres permitidos");
           }
        metodoLimpiar();
        ad.mostrarAlumnos(jtTablaAlumno);
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtApellidoActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed

        //        try {
        //
        //            if (jtDocumentodni.getText().equals("")) {
        //                JOptionPane.showMessageDialog(null, "Error: 'Buscar' el campo esta vacio");
        //
        //            } else {
        //                Alumno alumno = ad.buscarAlumnoPorDni(Integer.parseInt(jtDocumentodni.getText()));
        //                jtNombre.setText(alumno.getNombre());
        //                jtApellido.setText(alumno.getApellido());
        //                jrbEstado.setSelected(alumno.isActivo());
        //                jtcampofecha.setText(alumno.getFechaNacimiento() + "");
        //                jtid.setText(alumno.getIdAlumno() + ""); //probando
        //                Instant fecha;
        //                jdcFechaNac.setDateFormatString(alumno.getFechaNacimiento().toString());
        //
        //            }
        //
        //        } catch (NullPointerException ex) {
        //            JOptionPane.showMessageDialog(this, "el dni no existe en la base de datos");
        //            metodoLimpiar();
        //        } catch (NumberFormatException exe) {
        //            JOptionPane.showMessageDialog(this, "el DNI supero el limite de caracteres");
        //            metodoLimpiar();
        //        }
        ///////////////////////////////////////////////////////////////////////////////////////////////////
        //        AlumnoData aludata = new AlumnoData();
        //        Alumno alumno = aludata.buscarAlumnoPorDni(Integer.parseInt(jtDocumentodni.getText()));
        //
        //        if (!jtDocumentodni.getText().equalsIgnoreCase("")) {
        //            try {
        //
        //                if (alumno != null) {
        //                    jtApellido.setText(alumno.getApellido());
        //                    jtNombre.setText(alumno.getNombre());
        //                    jtcampofecha.setText(alumno.getFechaNacimiento() + "");
        //
        //                }
        //            } catch (NumberFormatException ex) {
        //                JOptionPane.showMessageDialog(null, "Solo puede Ingresar numeros en el campo DNI");
        //            }
        //        } else {
        //            JOptionPane.showMessageDialog(null, "no puede haber campos vacios");
        //        }
        //
        //jtDocumentodni.setText("");
        //        jtApellido.setText("");
        //        jtNombre.setText("");
        //
        //        jdcFechaNac.setCalendar(null);//seteo a vacio
        //        jrbEstado.setSelected(false);//seteo a vacio
        //
        //        boolean estado = alumno.isActivo();
        //        if (estado = true) {
        //            jrbEstado.setSelected(true);
        //        } else {
        //            jrbEstado.setSelected(false);
        //        }
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////
        //        try {
        //
        //            if (jtDocumentodni.getText().equals("")) {
        //                JOptionPane.showMessageDialog(null, "Error: 'Buscar' el campo esta vacio");
        //
        //            } else {
        //                Alumno alumno = ad.buscarAlumnoPorDni(Integer.parseInt(jtDocumentodni.getText()));
        //                jtNombre.setText(alumno.getNombre());
        //                jtApellido.setText(alumno.getApellido());
        //                jrbEstado.setSelected(alumno.isActivo());
        //                LocalDate lc = alumno.getFechaNacimiento();
        //                java.util.Date date = java.util.Date.from(lc.atStartOfDay(ZoneId.systemDefault()).toInstant());
        //                jdcFechaNac.setDate(date);
        //                jtid.setText(alumno.getIdAlumno() + ""); //probando
        //
        //            }
        //
        //        } catch (NullPointerException ex) {
        //            JOptionPane.showMessageDialog(this, "el dni no existe en la base de datos");
        //            metodoLimpiar();
        //        } catch (NumberFormatException exe) {
        //            JOptionPane.showMessageDialog(this, "el DNI supero el limite de caracteres");
        //            metodoLimpiar();
        //        }
        //////////////////////////////////////////////////////////////////////////////////////////////
        try {
            Integer dni = Integer.parseInt(jtDocumentodni.getText());
            Alumno alumnoActual = ad.buscarAlumnoPorDni(dni);

            if (alumnoActual != null) {

                jtApellido.setText(alumnoActual.getApellido());
                jtID.setText(String.valueOf(alumnoActual.getIdAlumno()));
                jtNombre.setText(alumnoActual.getNombre());
                jrbEstado.setSelected(alumnoActual.isActivo());
                LocalDate lc = alumnoActual.getFechaNacimiento();
                java.util.Date date = java.util.Date.from(lc.atStartOfDay(ZoneId.systemDefault()).toInstant());
                jdcFechaNac.setDate(date);

            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Usted debe ingresar un numero valido");
        }

    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jtDocumentodniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDocumentodniKeyReleased
        if (!jtDocumentodni.getText().isEmpty()) {

            jbGuardar.setEnabled(true);

        } else {
            jbGuardar.setEnabled(false);
        }
    }//GEN-LAST:event_jtDocumentodniKeyReleased

    private void jtDocumentodniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDocumentodniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDocumentodniActionPerformed

    private void jtTablaAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTablaAlumnoMouseClicked
        //        AlumnoData objetoAlumno = new AlumnoData();
        //
        //        objetoAlumno.seleccionarAlumnos(jtTablaAlumno, jtid, jtDocumentodni, jtApellido, jtNombre, jtcampofecha);
    }//GEN-LAST:event_jtTablaAlumnoMouseClicked

    private void metodoLimpiar() {
        jtDocumentodni.setText("");
        jtApellido.setText("");
        jtNombre.setText("");
//        jtcampofecha.setText("");
        jdcFechaNac.setCalendar(null);//seteo a vacio
        jrbEstado.setSelected(false);//seteo a vacio
        jtID.setText("");
    }

//    private LocalDate formatoFecha(){
//        if(jcalendario.getDate()!=null){
//            LocalDate fecha=jcalendario.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
//            return fecha;
//        }
//        return null;
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbLimpiar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbSalir;
    private com.toedter.calendar.JDateChooser jdcFechaNac;
    private javax.swing.JRadioButton jrbEstado;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtDocumentodni;
    private javax.swing.JTextField jtID;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTable jtTablaAlumno;
    // End of variables declaration//GEN-END:variables
}
