/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package universidadgrupo49.vistas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import universidadgrupo49.accesoADatos.AlumnoData;
import universidadgrupo49.accesoADatos.Conexion;
import universidadgrupo49.entidades.Alumno;

/**
 *
 * @author TenseiZX
 */
public class FormularioAlumno extends javax.swing.JInternalFrame {

    private AlumnoData ad;
    
    

    
    
    public FormularioAlumno(AlumnoData ad) {
        initComponents();
        AlumnoData objetoAlumno=new AlumnoData();
        objetoAlumno.mostrarAlumnos(jtTablaAlumno);
        this.ad = ad;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtDocumentodni = new javax.swing.JTextField();
        jtApellido = new javax.swing.JTextField();
        jtNombre = new javax.swing.JTextField();
        jrbEstado = new javax.swing.JRadioButton();
        jdcFechaNac = new com.toedter.calendar.JDateChooser();
        jbBuscar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jtcampofecha = new javax.swing.JTextField();
        jbModificar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTablaAlumno = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jtid = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(44, 22));

        jLabel1.setText("Alumno");

        jLabel2.setText("DNI:");

        jLabel3.setText("Apellido:");

        jLabel4.setText("Nombre:");

        jLabel5.setText("Estado");

        jLabel6.setText("Fecha de nacimiento:");

        jtDocumentodni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDocumentodniActionPerformed(evt);
            }
        });

        jtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtApellidoActionPerformed(evt);
            }
        });

        jdcFechaNac.setDateFormatString("yyyy-MM-dd");

        jbBuscar.setText("Buscar");
        jbBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarActionPerformed(evt);
            }
        });

        jbGuardar.setText("Guardar");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jtcampofecha.setEditable(false);
        jtcampofecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtcampofechaMouseClicked(evt);
            }
        });
        jtcampofecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcampofechaActionPerformed(evt);
            }
        });

        jbModificar.setText("Modificar:");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jtTablaAlumno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtTablaAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtTablaAlumnoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtTablaAlumno);

        jLabel7.setText("ID:");

        jtid.setEditable(false);
        jtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jbSalir)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jbGuardar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbModificar)
                                        .addGap(74, 74, 74)))
                                .addGap(45, 45, 45)
                                .addComponent(jbEliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(12, 12, 12)
                                            .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(18, 18, 18)
                                            .addComponent(jtDocumentodni, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtNombre)))
                                .addGap(17, 17, 17)
                                .addComponent(jbBuscar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jdcFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(23, 23, 23)
                                    .addComponent(jtcampofecha, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(16, 16, 16)
                                .addComponent(jtid, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(34, 34, 34)
                                .addComponent(jrbEstado))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(179, 179, 179)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jtDocumentodni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbBuscar))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jtcampofecha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbModificar)
                                    .addComponent(jdcFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5))
                            .addComponent(jrbEstado))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbGuardar)
                            .addComponent(jbEliminar))
                        .addGap(32, 32, 32)
                        .addComponent(jbSalir)))
                .addGap(0, 147, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtDocumentodniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDocumentodniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDocumentodniActionPerformed

    private void jtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtApellidoActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed

        
        
        try {
            
            ad.guardarAlumno(new Alumno(Integer.parseInt(jtDocumentodni.getText()), jtApellido.getText(), jtNombre.getText(), jdcFechaNac.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(), jrbEstado.isSelected()));
            ad.mostrarAlumnos(jtTablaAlumno);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "campos vacios");
        }

        jtDocumentodni.setText("");
        jtApellido.setText("");
        jtNombre.setText("");

        jdcFechaNac.setCalendar(null);//seteo a vacio
        jrbEstado.setSelected(false);//seteo a vacio
        
        

    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarActionPerformed

        if (jtDocumentodni.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "el campo esta vacio");
        } else {
            Alumno alumno = ad.buscarAlumnoPorDni(Integer.parseInt(jtDocumentodni.getText()));
            jtNombre.setText(alumno.getNombre());
            jtApellido.setText(alumno.getApellido());
            jtcampofecha.setText(alumno.getFechaNacimiento() + "");
            Instant fecha;
            jdcFechaNac.setDateFormatString(alumno.getFechaNacimiento().toString());

        }
///////////////////////////////////////////////////////////////////////////////////////////////////
//        AlumnoData aludata = new AlumnoData();
//        Alumno alumno = aludata.buscarAlumnoPorDni(Integer.parseInt(jtDocumentodni.getText()));
//
//        if (!jtDocumentodni.getText().equalsIgnoreCase("")) {
//            try {
//
//                if (alumno != null) {
//                    jtApellido.setText(alumno.getApellido());
//                    jtNombre.setText(alumno.getNombre());
//                    jtcampofecha.setText(alumno.getFechaNacimiento() + "");
//
//                }
//            } catch (NumberFormatException ex) {
//                JOptionPane.showMessageDialog(null, "Solo puede Ingresar numeros en el campo DNI");
//            }
//        } else {
//            JOptionPane.showMessageDialog(null, "no puede haber campos vacios");
//        }
//
//jtDocumentodni.setText("");
//        jtApellido.setText("");
//        jtNombre.setText("");
//
//        jdcFechaNac.setCalendar(null);//seteo a vacio
//        jrbEstado.setSelected(false);//seteo a vacio
//
//        boolean estado = alumno.isActivo();
//        if (estado = true) {
//            jrbEstado.setSelected(true);
//        } else {
//            jrbEstado.setSelected(false);
//        }


    }//GEN-LAST:event_jbBuscarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        int cambiarAInactivo=Integer.parseInt(jtDocumentodni.getText());
        if(ad.buscarAlumnoPorDni(cambiarAInactivo)!=null){
        int msj=JOptionPane.showConfirmDialog(this,"estas seguro que desea eliminar este alumno?");
        
        if(msj==0){
        ad.eliminarAlumno(ad.buscarAlumnoPorDni(cambiarAInactivo).getIdAlumno());
        ad.mostrarAlumnos(jtTablaAlumno);
        jtDocumentodni.setText("");
        jtApellido.setText("");
        jtNombre.setText("");
        jtcampofecha.setText("");
        jdcFechaNac.setCalendar(null);//seteo a vacio
        jrbEstado.setSelected(false);//seteo a vacio
        }
        
        }
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        
        
        AlumnoData objetoAlumno=new AlumnoData();
        
        
        
        try{


        objetoAlumno.ModificarAlumno(new Alumno(Integer.parseInt(jtid.getText()),Integer.parseInt(jtDocumentodni.getText()), jtApellido.getText(), jtNombre.getText(), jdcFechaNac.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(), jrbEstado.isSelected()));
        
        objetoAlumno.mostrarAlumnos(jtTablaAlumno);
        }catch (NumberFormatException ex){
        JOptionPane.showMessageDialog(null, "error ");
        }catch (NullPointerException ex){
        JOptionPane.showMessageDialog(null, "no puede haber campos vacios");
        }
        
        
        jtDocumentodni.setText("");
        jtApellido.setText("");
        jtNombre.setText("");
        jtcampofecha.setText("");
        jdcFechaNac.setCalendar(null);//seteo a vacio
        jrbEstado.setSelected(false);//seteo a vacio
        jtid.setText("");
        

        
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jtTablaAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtTablaAlumnoMouseClicked
        AlumnoData objetoAlumno=new AlumnoData();
        
        objetoAlumno.seleccionarAlumnos(jtTablaAlumno,jtid, jtDocumentodni, jtApellido, jtNombre, jtcampofecha);
        
    }//GEN-LAST:event_jtTablaAlumnoMouseClicked

    private void jtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtidActionPerformed

    private void jtcampofechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcampofechaActionPerformed
       
    }//GEN-LAST:event_jtcampofechaActionPerformed

    private void jtcampofechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtcampofechaMouseClicked
         String fecha=jtcampofecha.getText();
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        
        try {
            Date date= sdf.parse(fecha);
            jdcFechaNac.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(FormularioAlumno.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jtcampofechaMouseClicked


    
    
//    private LocalDate formatoFecha(){
//        if(jcalendario.getDate()!=null){
//            LocalDate fecha=jcalendario.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
//            return fecha;
//        }
//        return null;
//    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBuscar;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbSalir;
    private com.toedter.calendar.JDateChooser jdcFechaNac;
    private javax.swing.JRadioButton jrbEstado;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtDocumentodni;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTable jtTablaAlumno;
    private javax.swing.JTextField jtcampofecha;
    private javax.swing.JTextField jtid;
    // End of variables declaration//GEN-END:variables
}
